Request for code review
patriciachrysy/micro-reddit pull request #1
Opened 2020-05-01 09:56 UTC by patriciachrysy

Created the user, post, and comment models. Created the migration files for each model, build the relationship between them, added the validations,  and tested in the rails console.

2020-05-03 01:18 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @patriciachrysy  and @dili021 :balloon: :lollipop: 

### You've done a great job with this project, I like how well you explain the usage of your app :1st_place_medal: :1st_place_medal:  I would like you to do minor changes and add a little more to your Readme file so please keep reading

#### General

- [ ] Please add a product screenshot, even though you don't have views yet but it could be a screenshot from your console displaying the Users, Posts and Comments models

- [ ] Add and Usage section describing with examples how to create a Post a User and comments in the console (I think the content of your Run test section belongs to the Usage section)

- [ ] Include an Automated Test section in your Readme file even if it only says "there are no automated test for this project yet"

#### Project Specific

- [ ] I've put changes in your code below :point_down: 

### That's it, team! :raised_hands: 

### Please :pray: do the changes :woman_technologist:  :man_technologist: and submit back for a code review when you are done :memo: 

Happy Coding! :rocket: 

Any question? please ask on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-05-03 01:18 UTC, euqueme commented on README.md
> +- Use this command to make 'Test' user create a post: `User.first.create(url:'https://microverse.org', title:'Awesome bootcamp')`
- [ ] This command is giving this error let's fix it:

![image](https://user-images.githubusercontent.com/52209067/80896131-5237bb80-8ca8-11ea-95db-0c0f6726928b.png)

2020-05-03 01:18 UTC, euqueme commented on README.md
> +### Run tests
- [ ] This section should be called Usage instead of Run test

2020-05-03 01:18 UTC, euqueme commented on app/models/comment.rb
> +  validates :post, presence: true
- [ ] these validations are unnecessary because belongs_to already validates the presence

2020-05-03 01:18 UTC, euqueme commented on app/models/post.rb
> +  validates :user, presence: true
- [ ] this validation is unnecessary because belongs_to already validates the presence of a user

2020-05-04 16:35 UTC, patriciachrysy commented
Hello TSE,
changes in the readme file were applied and also removed useless validators in the post and comment models
Thanks for reviewing again

2020-05-05 19:09 UTC, shshamim63 commented
## Status :100: Approved :medal_military: 
___
Awesome job :clap: loved the readme you have generated. Truly well organized and each section contains appropriate information. Just one issue, I can see two rubocop gem in the gemfile line 20 and 34. So please remove one. After that, you are ready to go. This :+1: is from me in advance.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-06 08:21 UTC, merged